apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "discord-utility-bot"
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: "nodejs"
  template:
    metadata:
      labels:
        app: "nodejs"
    spec:
      containers:
        - name: "discord-utility-bot"
          image: "ghcr.io/tommymcgahee/tommymcgahee/utilitydiscordbot:latest"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: github-container-registry-secret